-- MySQL Script generated by MySQL Workbench
-- 02/10/15 20:15:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UnivercityMySql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UnivercityMySql` ;

-- -----------------------------------------------------
-- Schema UnivercityMySql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UnivercityMySql` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `UnivercityMySql` ;

-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Departments` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Departments` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Courses` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Courses` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Departments_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Departments_Id`),
  INDEX `fk_Courses_Departments1_idx` (`Departments_Id` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`Departments_Id`)
    REFERENCES `UnivercityMySql`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Professors` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Professors` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Departments_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Departments_Id`),
  INDEX `fk_Professors_Departments1_idx` (`Departments_Id` ASC),
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`Departments_Id`)
    REFERENCES `UnivercityMySql`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Faculties` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Students` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Students` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `MieddleName` VARCHAR(45) NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `FacultyNumber` VARCHAR(15) NOT NULL,
  `Faculties_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Students_Faculties_idx` (`Faculties_Id` ASC),
  CONSTRAINT `fk_Students_Faculties`
    FOREIGN KEY (`Faculties_Id`)
    REFERENCES `UnivercityMySql`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`AcademicalTitles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`AcademicalTitles` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`AcademicalTitles` (
  `idAcademicalTitles` INT NOT NULL AUTO_INCREMENT,
  `Titles` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idAcademicalTitles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`AcademicalTitles_has_Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`AcademicalTitles_has_Professors` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`AcademicalTitles_has_Professors` (
  `AcademicalTitles_idAcademicalTitles` INT NOT NULL,
  `Professors_Id` INT NOT NULL,
  PRIMARY KEY (`AcademicalTitles_idAcademicalTitles`, `Professors_Id`),
  INDEX `fk_AcademicalTitles_has_Professors_Professors1_idx` (`Professors_Id` ASC),
  INDEX `fk_AcademicalTitles_has_Professors_AcademicalTitles1_idx` (`AcademicalTitles_idAcademicalTitles` ASC),
  CONSTRAINT `fk_AcademicalTitles_has_Professors_AcademicalTitles1`
    FOREIGN KEY (`AcademicalTitles_idAcademicalTitles`)
    REFERENCES `UnivercityMySql`.`AcademicalTitles` (`idAcademicalTitles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AcademicalTitles_has_Professors_Professors1`
    FOREIGN KEY (`Professors_Id`)
    REFERENCES `UnivercityMySql`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Professors_has_Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Professors_has_Courses` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Professors_has_Courses` (
  `Professors_Id` INT NOT NULL,
  `Courses_Id` INT NOT NULL,
  PRIMARY KEY (`Professors_Id`, `Courses_Id`),
  INDEX `fk_Professors_has_Courses_Courses1_idx` (`Courses_Id` ASC),
  INDEX `fk_Professors_has_Courses_Professors1_idx` (`Professors_Id` ASC),
  CONSTRAINT `fk_Professors_has_Courses_Professors1`
    FOREIGN KEY (`Professors_Id`)
    REFERENCES `UnivercityMySql`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Courses_Courses1`
    FOREIGN KEY (`Courses_Id`)
    REFERENCES `UnivercityMySql`.`Courses` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Departments_has_Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Departments_has_Faculties` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Departments_has_Faculties` (
  `Departments_Id` INT NOT NULL,
  `Faculties_Id` INT NOT NULL,
  PRIMARY KEY (`Departments_Id`, `Faculties_Id`),
  INDEX `fk_Departments_has_Faculties_Faculties1_idx` (`Faculties_Id` ASC),
  INDEX `fk_Departments_has_Faculties_Departments1_idx` (`Departments_Id` ASC),
  CONSTRAINT `fk_Departments_has_Faculties_Departments1`
    FOREIGN KEY (`Departments_Id`)
    REFERENCES `UnivercityMySql`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departments_has_Faculties_Faculties1`
    FOREIGN KEY (`Faculties_Id`)
    REFERENCES `UnivercityMySql`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnivercityMySql`.`Courses_has_Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnivercityMySql`.`Courses_has_Students` ;

CREATE TABLE IF NOT EXISTS `UnivercityMySql`.`Courses_has_Students` (
  `Courses_Id` INT NOT NULL,
  `Students_Id` INT NOT NULL,
  PRIMARY KEY (`Courses_Id`, `Students_Id`),
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_Id` ASC),
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_Id` ASC),
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_Id`)
    REFERENCES `UnivercityMySql`.`Courses` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_Id`)
    REFERENCES `UnivercityMySql`.`Students` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
